#!/bin/sh

# When someone does a check, we always have a new version
exec 3>&1
exec 1>&2

export TMPDIR=${TMPDIR:-/tmp}
payload=$TMPDIR/multi-commit-resource
cat > $payload <&0

VERSION="000AAA"

echo "Check:" $VERSION
echo "Check:" $(cat $payload)

data="[ { \"ref\" : \"$VERSION\" } ]"

echo $data >&3
