#!/bin/sh

# When someone does a check, we always have a new version
exec 3>&1
exec 1>&2

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

mkdir -p $destination

export VERSION="000AAA"
export BUILD_URL=$ATC_EXTERNAL_URL"/teams/"$BUILD_TEAM_NAME"/pipelines/"$BUILD_PIPELINE_NAME"/jobs/"$BUILD_JOB_NAME"/builds/"$BUILD_ID

echo "In: ENV"
env
echo "In: ENV"

echo " In: destination:" $destination " version:" $VERSION " ::"

data="{                                                            \
        \"version\" : { \"ref\" : \"$VERSION\" },                  \
        \"metadata\" : [                                           \
                         {                                         \
                           \"name\" : \"BUILD_TEAM_NAME\",         \
                           \"value\" : \"$BUILD_TEAM_NAME\"        \
                         },                                        \
                         {                                         \
                           \"name\" : \"BUILD_ID\",                \
                           \"value\" : \"$BUILD_ID\"               \
                         },                                        \
                         {                                         \
                           \"name\" : \"BUILD_NAME\",              \
                           \"value\" : \"$BUILD_NAME\"             \
                         },                                        \
                         {                                         \
                           \"name\" : \"BUILD_JOB_NAME\",          \
                           \"value\" : \"$BUILD_JOB_NAME\"         \
                         },                                        \
                         {                                         \
                           \"name\" : \"BUILD_PIPELINE_NAME\",     \
                           \"value\" : \"$BUILD_PIPELINE_NAME\"    \
                         },                                        \
                         {                                         \
                           \"name\" : \"ATC_EXTERNAL_URL\",        \
                           \"value\" : \"$ATC_EXTERNAL_URL\"       \
                         },                                        \
                         {                                         \
                           \"name\" : \"URL\",                     \
                           \"value\" : \"$BUILD_URL\"              \
                         }                                         \
                       ]                                           \
                     }"

echo $data >$destination/in.json
echo $data >&3
