#!/bin/sh

exec 3>&1
exec 1>&2

output_dir=$1

if [ -z "$output_dir" ]; then
  echo "usage: $0 <output-directory>" >&2
  exit 1
fi

export TMPDIR=${TMPDIR:-/tmp}
payload=$TMPDIR/multi-commit-resource
cat > $payload <&0

mkdir -p $output_dir

# Do the needful 
data="{                                                            \
        \"version\" : { \"ref\" : \"000000\" },                    \
        \"metadata\" : [
                       ]                                           \
                     }"

echo $data >$output_dir/in.json
echo $data >&3
