#!/bin/sh

exec 3>&1
exec 1>&2

output_dir=$1

if [ -z "$output_dir" ]; then
  echo "usage: $0 <output-directory>" >&2
  exit 1
fi

export TMPDIR=${TMPDIR:-/tmp}
payload=$TMPDIR/multi-commit-resource
cat > $payload <&0

cat $payload

mkdir -p $output_dir

export BUILD_URL=$ATC_EXTERNAL_URL"/teams/"$BUILD_TEAM_NAME"/pipelines/"$BUILD_PIPELINE_NAME"/jobs/"$BUILD_JOB_NAME"/builds/"$BUILD_NAME

data="{                                                            \
        \"version\" : { \"ref\" : \"000000\" },                    \
        \"metadata\" : [                                           \
                         {                                         \
                           \"name\" : \"URL\",                     \
                           \"value\" : \"$BUILD_URL\"              \
                         }                                         \
                       ]                                           \
                     }"

echo $data >$output_dir/out.json
echo $data >&3
